# yaml 配置
version: '3'
services:
  frontend:
    image: zzuisa/due_admission_web:latest
    ports:
      - "8000:80"
    depends_on:
      - nginx
    networks:
      - common
    restart: always
  backend:
    image: zzuisa/due_admission_backend:latest
    ports:
      - "888:888"
    depends_on:
      - mysql
      - nginx
    volumes:
      - ./uploads:/usr/local/share/fileupload
    networks:
      - common
    restart: always
  nginx:
    image: "nginx:alpine"
    container_name: pro_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 81:80
      - 8001:8001
    networks:
      - common
    restart: always
  mysql:
    image: mysql:5.7.32
    container_name: pro_mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      - MYSQL_ROOT_PASSWORD=sa0230
      - MYSQL_DATABASE=due_admission
    ports:
      - 3304:3306
    networks:
      - common
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: always
volumes:
  mysqlData:
  mysqlConf:
  nginxConf:
networks:
  common:
